version: 0.1

phases: 
    build:
        commands:
            - npm install
            - npm run webpack
artifacts:
    files:
        - index.html
        - favicon.ico
        - Amadou_Lamine_Gaye_CV_wsm.pdf
        - styles/*
        - images/*
        - dist/bundle.js